// File generated by flutterfire configure.
// DO NOT EDIT.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWeb',
    appId: '1:1035669922634:web:dummy',
    messagingSenderId: '1035669922634',
    projectId: 'smart-clockin-presensi',
    authDomain: 'smart-clockin-presensi.firebaseapp.com',
    storageBucket: 'smart-clockin-presensi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE18oJ6RXbz8F-SNnQuk6QXo7plCyzqfA',
    appId: '1:1035669922634:android:2df05fc531e2976cec97b3',
    messagingSenderId: '1035669922634',
    projectId: 'smart-clockin-presensi',
    storageBucket: 'smart-clockin-presensi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS',
    appId: '1:1035669922634:ios:dummy',
    messagingSenderId: '1035669922634',
    projectId: 'smart-clockin-presensi',
    storageBucket: 'smart-clockin-presensi.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTugasakhirPresensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForMacOS',
    appId: '1:1035669922634:macos:dummy',
    messagingSenderId: '1035669922634',
    projectId: 'smart-clockin-presensi',
    storageBucket: 'smart-clockin-presensi.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTugasakhirPresensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindows',
    appId: '1:1035669922634:windows:dummy',
    messagingSenderId: '1035669922634',
    projectId: 'smart-clockin-presensi',
    storageBucket: 'smart-clockin-presensi.firebasestorage.app',
  );
}
